apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: .
      repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
      targetRevision: 0.13.0
      helm:
        releaseName: arc-runner-set
        valueFiles:
          - $values/bernats-standard-services/values/arc-runner-set.yaml
        parameters:
          - name: githubConfigUrl
            value: {{ .Values.githubOrgUrl }}
    - repoURL: {{ .Values.sourceRepoUrl }}
      targetRevision: main
      ref: values
  destination:
    namespace: arc-runners
    server: {{ .Values.argocdDestinationServer }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
