apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.7.22
      helm:
        releaseName: argocd
    - repoURL: {{ .Values.sourceRepoUrl }}
      targetRevision: main
      ref: values
  destination:
    namespace: argocd
    server: {{ .Values.argocdDestinationServer }}
