apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: 0.5.0
      helm:
        releaseName: cnpg-database
        valueFiles:
          - $values/bernats-standard-services/values/cloudnative-pg-cluster.yaml
    - repoURL: {{ .Values.sourceRepoUrl }}
      targetRevision: main
      ref: values
  destination:
    namespace: cnpg-database
    server: {{ .Values.argocdDestinationServer }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/