apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 24.4.9
      helm:
        releaseName: keycloak
        valueFiles:
          - $values/bernats-standard-services/values/keycloak.yaml
        parameters:
          - name: ingress.hostname
            value: keycloak.{{ .Values.ingressHostname }}
    - repoURL: {{ .Values.sourceRepoUrl }}
      targetRevision: main
      ref: values
  destination:
    namespace: keycloak
    server: {{ .Values.argocdDestinationServer }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
