# https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-kube-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-kube-stack
      targetRevision: 0.12.6
      helm:
        releaseName: opentelemetry-stack
        valueFiles:
          - $values/bernats-standard-services/values/otel-kube-stack.yaml
    - repoURL: {{ .Values.sourceRepoUrl }}
      targetRevision: main
      ref: values
  destination:
    namespace: opentelemetry-operator-system
    server: {{ .Values.argocdDestinationServer }}
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle