apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standard-services
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    path: bernats-standard-services
    repoURL: https://github.com/bernats-homelab/kubernetes-standard-services
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
