grafana:
  defaultDashboardsTimezone: utc-3
  defaultDashboardsEditable: false
  ingress:
    enabled: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    enabled: true
    enableNewTablePanelSyntax: true
    default:
      argocd-operational:
        gnetId: 19993
        revision: 3
        datasource: Prometheus
      argocd-notifications:
        gnetId: 19975
        revision: 3
        datasource: Prometheus
      argocd-application:
        gnetId: 19974
        revision: 3
        datasource: Prometheus
      nginx-overview:
        gnetId: 16677
        revision: 2
        datasource: Prometheus
      nginx-request-handling:
        gnetId: 20510
        revision: 2
        datasource: Prometheus
      cert-manager:
        url: https://raw.githubusercontent.com/monitoring-mixins/website/refs/heads/master/assets/cert-manager/dashboards/overview.json
        token: ""
