grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.192.168.1.19.nip.io

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    argocd-operational:
      gnetId: 19993
      revision: 3
      datasource: Prometheus
    argocd-notifications:
      gnetId: 19975
      revision: 3
      datasource: Prometheus
    argocd-application:
      gnetId: 19974
      revision: 3
      datasource: Prometheus
